import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { agentService } from "../services/agent.service.js";

/**
 * Path parameter schema for /api/agents/{agentId}/run
 */
export const RunAgentParamsSchema = z.object({
  agentId: z.string().openapi({
    param: {
      name: "agentId",
      in: "path",
    },
    example: "contextflow-assistant",
    description: "The unique identifier of the agent to execute",
  }),
});

/**
 * Request body schema for executing an agent.
 */
export const RunAgentRequestSchema = z
  .object({
    message: z.string().min(1, "Message must not be empty").openapi({
      example: "What is ContextFlow?",
      description: "User message or prompt for the agent",
    }),
  })
  .openapi("RunAgentRequest");

/**
 * Response schema for a successful agent execution.
 */
export const RunAgentResponseSchema = z
  .object({
    agentId: z.string().openapi({
      example: "contextflow-assistant",
      description: "The identifier of the agent that executed the run",
    }),
    text: z.string().openapi({
      example: "ContextFlow is an application-agnostic AI agent execution and context layer.",
      description: "Normalized response text generated by the agent",
    }),
  })
  .openapi("RunAgentResponse");

/**
 * Standard error response schema.
 */
export const ErrorResponseSchema = z
  .object({
    error: z.string().openapi({
      example: "Agent 'unknown' not found",
      description: "Error message describing the failure",
    }),
  })
  .openapi("ErrorResponse");

/**
 * POST /api/agents/{agentId}/run
 * Executes a specified agent with the provided user message.
 */
export const runAgentRoute = createRoute({
  method: "post",
  path: "/api/agents/{agentId}/run",
  tags: ["Agents"],
  summary: "Run an agent",
  description:
    "Executes a specified agent through Mastra and returns the normalized response output.",
  request: {
    params: RunAgentParamsSchema,
    body: {
      content: {
        "application/json": {
          schema: RunAgentRequestSchema,
        },
      },
    },
  },
  responses: {
    200: {
      description: "Agent executed successfully",
      content: {
        "application/json": {
          schema: RunAgentResponseSchema,
        },
      },
    },
    400: {
      description: "Validation error — invalid request body or path parameter",
      content: {
        "application/json": {
          schema: ErrorResponseSchema,
        },
      },
    },
    404: {
      description: "Agent not found",
      content: {
        "application/json": {
          schema: ErrorResponseSchema,
        },
      },
    },
    500: {
      description: "Agent execution or model provider failure",
      content: {
        "application/json": {
          schema: ErrorResponseSchema,
        },
      },
    },
  },
});

export const agentsRouter = new OpenAPIHono();

agentsRouter.openapi(runAgentRoute, async (c) => {
  const { agentId } = c.req.valid("param");
  const { message } = c.req.valid("json");

  // Unknown agent check
  const agent = agentService.resolveAgent(agentId);
  if (!agent) {
    return c.json({ error: `Agent '${agentId}' not found` }, 404);
  }

  // Execute agent with error boundary
  try {
    const result = await agentService.runAgent(agentId, { message });
    if (!result) {
      return c.json({ error: `Agent '${agentId}' not found` }, 404);
    }
    return c.json(result, 200);
  } catch (error) {
    console.error(`[AgentsRoute] Execution failed for agent '${agentId}':`, error);
    return c.json(
      { error: "Agent execution failed due to an underlying model provider error." },
      500,
    );
  }
});
